#!/bin/bash
# Dae-Yong, romanity2014@gmail.com
# 2017/10/09

# Install PYTHON2
sudo apt-get -y install python
sudo apt-get -y install python-pip

# Install Virtual Environment
sudo pip install virtualenv
virtualenv -p python venv

source venv/bin/activate
