#!/bin/bash
# Dae-Yong, romanity2014@gmail.com
# 2017/09/25

pip install --upgrade pip
pip install --upgrade -r requirements.txt

#pip3 install --upgrade pip
#pip3 install --upgrade -r requirements.txt

